name: EconomyProperty
main: onebone\economyproperty\EconomyProperty
version: "2.0.6"
author: onebone
api:
- 4.0.0

depend:
- EconomyLand
- EconomyAPI

permissions:
 economyproperty.property.modify:
  description: Allows player to modify property area
  default: op
 economyproperty.property.remove:
  description: Allows player to remove property
  default: op
 economyproperty.command.property.pos1:
  default: op
  description: Allows player to use /property pos1 command
 economyproperty.command.property.pos2:
  default: op
  description: Allows player to use /property pos2 command
 economyproperty.command.property.make:
  default: op
  description: Allows player to use /property make command
