name: EconomyShop
version: "2.0.7"
api:
- 4.0.0

main: onebone\economyshop\EconomyShop
author: onebone
depend: [EconomyAPI]

commands:
 shop:
  description: Management command for creating/removing shop
  usage: /shop <create|remove|list> [item[:damage]] [amount] [price] [side]
  permission: economyshop.command.shop.create;economyshop.command.shop.remove;economyshop.command.shop.list

permissions:
 economyshop.command.shop.create:
  description: Allows player to use /shop create
 economyshop.command.shop.remove:
  description: Allows player to use /shop remove
 economyshop.command.shop.list:
  description: Allows player to use /shop list
  default: true
 economyshop.shop.buy:
  description: Allows player to buy from shop
  default: true
