name: EconomyUsury
version: "1.0.1"
author: onebone
api:
- 4.0.0

main: onebone\economyusury\EconomyUsury
depend: [EconomyAPI]

permissions:
 economyusury.command.usury.host.open:
  description: Gives player permission to open usury host by command
  default: true
 economyusury.command.usury.host.close:
  description: Gives player permission to close usury host by command
